### ISSUE TITLE
Driver no longer captures STDOUT of LaTeX sub-processes

### ISSUE THREAD

**Issue by ehuelsmann** [Template-Toolkit-Latex/LaTeX-Driver#4]
Before, the driver would use IPC::ShellCmd which captures both STDOUT and STDERR. Now, the subprocesses get started with ```system()``` calls, without redirection at all.

This leads to breakage in the LedgerSMB project (see ledgersmb/LedgerSMB#1426).

**Comment by einhverfr** [comment]
This was closed in the latest PR, correct?

**Comment by ehuelsmann** [comment]
correct.
